// Kitap türleri listesi (Alfabetik Isimli)
const List<String> bookGenres = [
  'Bilim Kurgu',
  'Biyografi / Anı',
  'Çocuk',
  'Deneme',
  'Din & İnanç',
  'Edebiyat Klasikleri',
  'Eğitici',
  'Ekonomi & Finans',
  'Etkinlik / Bulmaca',
  'Fantastik',
  'Felsefe',
  'Gençlik',
  'Gerilim / Thriller',
  'Gezi',
  'Grafik Roman / Çizgi Roman',
  'İlk Okuma',
  'İş Dünyası & Yönetim',
  'Kişisel Gelişim',
  'Korku',
  'Masal & Mitoloji',
  'Okul Öncesi',
  'Öykü',
  'Polisiye & Dedektif',
  'Popüler Bilim',
  'Psikoloji',
  'Roman',
  'Romantik',
  'Siyaset',
  'Sosyoloji',
  'Tarih',
  'Tarihî Kurgu',
];
